---
- name: Add corretto Deb822 Repo
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
  loop: "{{ _aws_jdk.deb822_repository | default([]) }}"

- name: Install latest Aws JDK version # noqa package-latest
  ansible.builtin.apt:
    state: latest
    name: "{{ _aws_jdk.package_name }}"
    update_cache: yes
  when: not _aws_jdk.package_name is search('=')

- name: Install specific Aws JDK version
  ansible.builtin.apt:
    state: present
    name: "{{ _aws_jdk.package_name }}"
    update_cache: yes
  when: _aws_jdk.package_name is search('=')

- name: Find Corretto Java SDK directories
  ansible.builtin.find:
    paths: /usr/lib/jvm
    file_type: directory
    patterns:
      - '*corretto*'
    depth: 1
  register: corretto_dirs

- name: "Set security setting for DNS cache ttl"
  ansible.builtin.lineinfile:
    path: "{{ item.path }}/conf/security/java.security"
    regexp: '^(.*)networkaddress.cache.ttl=(.*)$'
    line: "networkaddress.cache.ttl={{ _aws_jdk.security.dns_cache_ttl }}"
  loop: "{{ corretto_dirs.files }}"
  when: corretto_dirs.matched > 0

- name: "Set security setting for DNS cache negative ttl"
  ansible.builtin.lineinfile:
    path: "{{ item.path }}/conf/security/java.security"
    regexp: '^(.*)networkaddress.cache.negative.ttl=(.*)$'
    line: "networkaddress.cache.negative.ttl={{ _aws_jdk.security.dns_cache_negative_ttl }}"
  loop: "{{ corretto_dirs.files }}"
  when: corretto_dirs.matched > 0
